### ISSUE TITLE
[Question] How to connect neo4j behind traefik with CA certificate  

### ISSUE THREAD

**Issue by jkandasa** [neo4j/neo4j-go-driver#120]
```
Neo4j version: Community  4.1.0
Neo4j Mode: Single instance
Driver version: github.com/neo4j/neo4j-go-driver v1.8.0
Operating system: Linux
```

### **Steps to reproduce**
* Setup a neo4j behind traefik with valid CA certificate
* Access neo4j with GoLang client

##### config:
```
uri: bolt://neo4jdb.*******.com:443
username: neo4j
password: ****
encrypted: true
```
##### code:
```
driver, err := n4j.NewDriver(cfg.URI, n4j.BasicAuth(cfg.Username, cfg.Password, ""),
		func(c *n4j.Config) {
			c.Encrypted = cfg.Encrypted
			c.Log = getLogger()
		},
	)
```
##### Traefik IngressRoute rule
```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  namespace: default
  name: neo4j-route
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`neo4j.****.com`)
    kind: Rule
    services:
    - name: neo4j
      port: 7474
  - match: HostSNI(`neo4jdb.****.com`)
    kind: Rule
    services:
    - name: neo4j
      port: 7687
  tls:
    certResolver: default

```

#### Expected behavior
* Connection should be established 

#### Actual behavior
* connection timeout

### Additional notes
I tried on the neo4j console. It is connected properly.
On the UI it uses `neo4j+s` or `bolt+s` protocol. Both protocols works well.
But in GoLang driver `neo4j+s`, `bolt+s` protocol not supported.

#### Screenshots

![neo4j1](https://user-images.githubusercontent.com/1004403/87502047-3e341100-c67e-11ea-83e2-1e05c7654d21.jpg)
---
![neo4j2](https://user-images.githubusercontent.com/1004403/87502240-ba2e5900-c67e-11ea-8b88-a4bf7b78b37a.jpg)
